### ISSUE TITLE
Problem with Age Matters

### ISSUE THREAD

**Issue by sdfg2** [emipa606/RFRimDisorders#1]
Babies constantly get PTSD because they are 'downed' by the Age Matters mod.  Could you maybe add an age check to getting it?

(I am amused by the philosophical idea that everyone has PTSD from just being a baby though XD )

**Comment by emipa606** [comment]
Can you link to the mod in question?

**Comment by sdfg2** [comment]
Sure! https://steamcommunity.com/sharedfiles/filedetails/?id=2264291966&searchtext=age+matters

**Comment by emipa606** [comment]
Should be fixed in f27a49b
Thanks for reporting!

**Comment by sdfg2** [comment]
I'm still having this problem.  I thought at first Steam just hadn't updated the mod, but the spacing is now correct on the messages so I know I'm up to date.

**Comment by emipa606** [comment]
strange, they should be excluded from the ptsd breaks if they have the babie-hediff?

**Comment by sdfg2** [comment]
Ah, is that how you did it?  No, they are toddlers now.  I would suggest it shouldn't affect Baby, Toddler or Child hediffs, only affecting Teenager onwards.

**Comment by emipa606** [comment]
I see, then it should be fixed in 1fe80cc

**Comment by sdfg2** [comment]
Thanks!

And also a huge thank you for taking up and maintaining all the mods you do - almost every time I get sad seeing an interesting one that I would like that is for an old version of RW, there you are, next option down continuing it :-)  You remind me a lot of linuxgurugamer on KSP actually hah

**Comment by emipa606** [comment]
No problem!

**Comment by sdfg2** [comment]
I had another one related to this - when someone gives birth they are downed and usually end up with PTSD.  Probably a bit harder to figure out this one though :-(

**Comment by emipa606** [comment]
I dont see anything about giving birth in Age Matters, is there another mod that adds that?

**Comment by sdfg2** [comment]
Oh hah yes sorry: Children, school and learning (https://steamcommunity.com/sharedfiles/filedetails/?id=1541438230&searchtext=children)

Was it just PTSD you turned off for babies, children and teenagers?

![image](https://user-images.githubusercontent.com/5736478/163588657-ca30d55a-959d-476e-a7b4-3661facd5754.png)

**Comment by emipa606** [comment]
Okay, added support for the birth in CSL: 266855e
and yes only for PTSD as you requested.
